services:
  accountmanagement:
    image: accountmanagement
    build:
      context: .
      dockerfile: AccountManagement/Dockerfile

  authorizationservice:
    image: authorizationservice
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile

