services:
  postgres_db:
    image: postgres:16
    container_name: homeapps-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  accountmanagement:
    image: accountmanagement
    build:
      context: .
      dockerfile: AccountManagement/Dockerfile

  authorizationservice:
    image: authorizationservice
    build:
      context: .
      dockerfile: AuthorizationService/Dockerfile

